# Generated by Django 5.1.7 on 2025-03-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default='come on', max_length=500),
            preserve_default=False,
        ),
    ]
